### ISSUE TITLE
Hammerspoon Lua Errors

### ISSUE THREAD

**Issue by klaus385** [Braden1996/BradensPoon#10]
Traceback ->

2018-03-21 09:11:52: -- Lazy extension loading enabled
2018-03-21 09:11:52: -- Loading ~/.hammerspoon/init.lua
2018-03-21 09:11:52: *** ERROR: error loading module 'init' from file '/Users/sklaus/.hammerspoon/init.lua':
	/Users/sklaus/.hammerspoon/init.lua:2: too many C levels (limit is 200) in main function near 'package'
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	...
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/sklaus/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by klaus385** [comment]
Though when I move all to the files under BradensPoon into ~/.hammerspoon. It works and loads the configuration properly.

**Comment by Braden1996** [comment]
Hey @klaus385, sorry to hear you're having issues!

This is usually caused by a misconfiguration in your `~/.hammerspoon/init.lua` file, such that it cannot find where you installed Hammerspoon. Could you let me know the contents of your file, and the output of `tree` (you may need to install it first `brew install tree`) within your installed BradensPoon directory?

**Comment by thu-zxs** [comment]
Same bug heres. It' s caused by missing a '/' at the end of the path. Great works though!
