### ISSUE TITLE
After following tutorial, nothing appears to be happening

### ISSUE THREAD

**Issue by mr-sk** [Braden1996/BradensPoon#4]
Hello, 

So I followed the steps as outlined in your github:

```
pwd
/Users/sk/Work/BradensPoon
tree -d
.
├── lua_modules
│   ├── lib
│   │   ├── lua
│   │   │   └── 5.3
│   │   └── luarocks
│   │       └── rocks-5.3
│   │           ├── luafilesystem
│   │           │   └── 1.7.0-2
│   │           │       ├── doc
│   │           │       │   └── us
│   │           │       └── tests
│   │           └── penlight
│   │               └── 1.5.4-1
│   │                   └── doc
│   │                       └── manual
│   └── share
│       └── lua
│           └── 5.3
│               └── pl
├── spoons
└── utils
    └── factories
```

And my:

```
cat ~/.hammerspoon/init.lua
local yourPath = '/Users/sk/Work/BradensPoon/'
package.path = yourPath .. '?.lua;' .. package.path;
require('init')
```

However, I don't see how to trigger the window to draw? 

I tried the "Hello World" in the Hammerspoon README and it works, so I know I have things wired up mostly correct. 

Thanks.

**Comment by Braden1996** [comment]
Hey @mr-sk, sorry to hear you're having issues!
To draw a terminal window, hold `shift` + `ctrl` simultaneously and move your cursor (no need to mouse-click). If that doesn't work, could you let me know the contents of the Hammerspoon console?
You can find the console by clicking on the Hammerspoon icon within the menubar.

**Comment by egregius313** [comment]
@Braden1996 I had the same issue. Then I tried using `shift` + `ctrl` and now it flashes a terminal window, and then it disappears and the only way I can interact with it is through `⌘` key.

**Comment by Braden1996** [comment]
@egregius313, hmm... I've sometimes had this same issue if I just press `shift` + `ctrl`. You need to hold it down whilst you drag your terminal window. Otherwise, it will be created with a size of 0.
Let me know if this helps :)

**Comment by mr-sk** [comment]
Works now after a reboot. Maybe the config wasn't being fully loaded. Thanks for the quick response guys.
