### ISSUE TITLE
Windows not Appearing on Ctrl + Shift

### ISSUE THREAD

**Issue by arjunchhabra** [Braden1996/BradensPoon#9]
Getting this error when I attempt to use the provided settings...looks like an infinite loop?

`
2018-03-14 23:06:05: -- Lazy extension loading enabled
2018-03-14 23:06:06: -- Loading ~/.hammerspoon/init.lua
2018-03-14 23:06:06: *** ERROR: error loading module 'init' from file'/Users/username/.hammerspoon/init.lua':
	/Users/username/.hammerspoon/init.lua:2: too many C levels (limit is 200) in main function near 'package'
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	...
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:545: in function 'require'
	/Users/username/.hammerspoon/init.lua:3: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)
`

Any help would be appreciated. I believe I followed the instructions correctly but let me know if there's anything I can do to verify.

**Comment by Braden1996** [comment]
Hey @arjunchhabra, sorry to hear you're having trouble!
Could you let me know the contents of your `./.hammerspoon/init.lua` file?
Also, confirm the `pwd` of where you installed BradensPoon.

This error typically happens if we cannot find your BradensPoon installation.

**Comment by arjunchhabra** [comment]
Thanks for stopping by to help! 

In ~/.hammerspoon/init.lua, I have the following:

`local yourPath = '/Users/username/Development/braden-hammerspoon'`
`package.path = yourPath .. '?.lua;' .. package.path;`
`require('init')`

and BradensPoon is located at 

/Users/username/Development/braden-hammerspoon

Any help would be great!

**Comment by Braden1996** [comment]
@arjunchhabra, looks like you're missing a trailing slash in `~/.hammerspoon/init.lua`, i.e.
```lua
local yourPath = '/Users/username/Development/braden-hammerspoon/'
```

Let me know if this helps :)

**Comment by arjunchhabra** [comment]
@Braden1996 

Ah! I hope it's something as simple as that. I tried your suggestion, updating my .lua to the following:

`local yourPath = '/Users/username/Development/braden-hammerspoon/'`
`package.path = yourPath .. '?.lua;' .. package.path;`
`require('init')`

but it produces the following error...

https://pastebin.com/hrtsGmS9

Thanks for your ongoing help!

**Comment by Braden1996** [comment]
I see you've changed the directory name for the installation. Did you account for this for each step within the readme? In particular:
```sh
cd BradensPoon
luarocks install --tree lua_modules penlight
```

Your `braden-hammerspoon` directory should look like this:
```
├── README.md
├── config
│   ├── default.lua
│   ├── init.lua
│   └── personal.lua
├── dependencies.lua
├── init.lua
├── init_helper.lua
├── lua_modules
│   ├── bin
│   ├── lib
│   └── share
├── spoons
│   ├── drag_terminals.lua
│   └── init.lua
└── utils
    ├── colors.lua
    ├── init.lua
    └── math.lua
```

**Comment by arjunchhabra** [comment]
@Braden1996 

Re-cloned the directory with the original name, re ran the luarocks command and reloaded config in Hammerspoon - success!

... however when I actually attempt to drag to create a terminal window, no luck. Is there a log file I could take a look at to see why the windows are't being generated?

**Comment by Braden1996** [comment]
@arjunchhabra, there is only the Hammerspoon console.
To create windows, you must use `ctrl + shift` (then just drag, no need to click).

**Comment by arjunchhabra** [comment]
@Braden1996 done all of the above, but still no terminal windows being created :/

This is my console output:

https://pastebin.com/Kanhyibc

(after the line reading "Done.", I attempt to create a new window on my desktop using ctrl+shift - then receive the final two messages.)

I think we're almost there!

**Comment by Braden1996** [comment]
@arjunchhabra, would you be able to share the current contents of your `~/.hammerspoon/init.lua` file?  Also, the `pwd` and `tree` of the directory in which you've installed BradensPoon. Also, the contents of `BradensPoons/config/personal.lua` could help.

**Comment by arjunchhabra** [comment]
@Braden1996 thanks for your continuing support!

~/.hammerspoon/init.lua: https://pastebin.com/kXrjRX9f
pwd & tree of BradensPoon: https://pastebin.com/C4hvQ1Ha
contents of personal.lua: https://pastebin.com/S7Z0N4CS

Thanks again.

**Comment by arjunchhabra** [comment]
Update: not sure what changed, but - all is working now! Thanks for your help and I'll post back here if I figure out what led to it breaking (or working again!)
